spring.application.name=employee-registration

spring.datasource.url=jdbc:postgresql://localhost:5432/employee-registration
spring.datasource.username=postgres
spring.datasource.password=8393
spring.datasource.driver-class-name=org.postgresql.Driver
pincode.api.url=http://www.postalpincode.in/api/pincode/

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
